### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by alfredonodo** [sky-ring/ton-house#1]
Hi,
very good work. I have some questions:

- Will TONHouse become the official network monitor of ton.org?
- Google fonts is outlawed in the EU. Could you replace remote Google fonts with a local copy to comply with GDPR and to protect user privacy?

Some future improvements:

- circulating, total and max supply;
- current and max inflation rate;
- current and maximum block time;
- current and average transaction fee;
- number of wallets and distribution of coins;
- staked value (validators and users);
- validators' stake and cumulative shake for the key values of the consensus algorithm (33% and 67%).

Thanks again

**Comment by shayan-shojaei** [comment]
Hey @alfredonodo.
I wasn't aware of the Google fonts issue, but we can take care of that. thanks for letting me know!
Also thank you for the suggestions, I really appreciate them and will try to implement as many of them as possible for the following milestones.

**Comment by chakzefir** [comment]
Would be great to have an opportunity to inspect concrete time periods over the timelines. Thought I think you already aware about this feature, I just wanted to make sure you have it in a spotlight 😉

**Comment by shayan-shojaei** [comment]
> Would be great to have an opportunity to inspect concrete time periods over the timelines. Thought I think you already aware about this feature, I just wanted to make sure you have it in a spotlight 😉

Yes, this is already implemented for the validators' info chart on the back end, the controls to actually change the time window are not there just yet, although they are really important as well. Thanks for pointing it out!

**Comment by alfredonodo** [comment]
Thank you for removing Google tracking through its fonts. I guess the rest of the improvements will be part of milestone 2 along with the data you listed in the roadmap.

**Comment by shayan-shojaei** [comment]
> Thank you for removing Google tracking through its fonts. I guess the rest of the improvements will be part of milestone 2 along with the data you listed in the roadmap.

Hi. Yes that's what I'm planning to do. I'm a bit swamped with work and school at the moment, but I'm planning to get to those in a couple of weeks and I would also appreciate any contributions, whether it be code or just suggestions!

**Comment by alfredonodo** [comment]
> > Thank you for removing Google tracking through its fonts. I guess the rest of the improvements will be part of milestone 2 along with the data you listed in the roadmap.
> 
> Hi. Yes that's what I'm planning to do. I'm a bit swamped with work and school at the moment, but I'm planning to get to those in a couple of weeks and I would also appreciate any contributions, whether it be code or just suggestions!

Take your time to do a good job. Unfortunately, I am unable to help you with the coding, but I can suggest that you follow the network status of other projects, I think [Solana beach](https://solanabeach.io/) is one of the best.

**Comment by alfredonodo** [comment]
Hi,
do you have any updates on milestone 2 of the roadmap? This data and in particular the circulating and total supply are very important for the transparency of the project.
Thank you
