### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by alfredonodo** [sky-ring/ton-house#2]
Hi,
the website with the statistics https://tonhouse.skyring.io/ is offline. Are there any problems?
Do you have any updates on the roadmap?
Thank you

**Comment by shayan-shojaei** [comment]
Hi. Thanks for creating the issue.
The problem is now resolved and the website is back up.
There was a problem with the server and I had to change the setup.

**Comment by alfredonodo** [comment]
The project site has been offiline for some time and the roadmap has not been completed.
Is there any news on this?
Thank you
